# Site settings
title: Portfolio Site for Dane Sherrets
description: Portfolio for Dane Sherrets
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dane Sherrets
user_description: Tinkerer passionate about securing the internet, advancing blockchain technology, and building cool stuff.
user_title: Blockchain Developer / Security Researcher 
email: DaneSherrets1990@gmail.com
twitter_username: DaneSherrets
github_username:  Gonzo-Code
gplus_username:  Dane Sherrets

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
